substitutions:
  name: air-alarm1
  friendly_name: airalarm1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.mcu: esp32s2
    board_build.variant: esp32s2
    board_build.f_cpu: 240000000

packages:
  - !include common/air-alarm-common.yaml
