substitutions:
  name: air-alarm
  friendly_name: airalarm

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.mcu: esp32s2
    board_build.variant: esp32s2

packages:
  - !include common/air-alarm-common.yaml
