substitutions:
  name: water-monitor
  friendly_name: Water Monitor

api:
  encryption:
    key: !secret water-monitor_api_encryption_key

packages:
  - !include external_components/esphome-toybox/water-monitor-mprls.yaml
  # mprls:
  #   url: https://github.com/GabrielGoldsteinAnidea/esphome-toybox
  #   ref: master
  #   file: water-monitor-mprls.yaml
  #   refresh: 0d

external_components:
  - source:
      # type: git
      # url: https://github.com/GabrielGoldsteinAnidea/esphome-toybox
      # ref: master
      type: local
      path: external_components/esphome-toybox/components
    components:
      - mprls
