# https://github.com/kbx81/esphome-configs/blob/main/shared/esp__common_core.yaml

# esphome:
#   friendly_name: ${node_friendly_name}
#   name: ${node_name}
#   project:
#     name: kbx81.${project_name}
#     version: ${project_version}
#   build_path: ../../build/${node_name}

preferences:
  flash_write_interval: 2min

# captive_portal:

improv_serial:

# Enable logging
logger:

button:
  - platform: restart
    name: Restart
    entity_category: diagnostic
  - platform: factory_reset
    name: Wipe Preferences
    entity_category: diagnostic

sensor:
  - platform: wifi_signal
    name: Wi-Fi Signal
    entity_category: diagnostic
    update_interval: 15s

  - id: _uptime
    platform: uptime
    name: Uptime
